# Generated by Django 5.1.6 on 2025-02-13 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='类别名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '资产类别',
                'verbose_name_plural': '资产类别',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='资产名称')),
                ('code', models.CharField(blank=True, help_text='留空将自动生成', max_length=50, unique=True, verbose_name='资产编号')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('status', models.CharField(choices=[('in_use', '使用中'), ('idle', '闲置'), ('maintenance', '维修中'), ('scrapped', '已报废')], default='idle', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='assets.assetcategory', verbose_name='资产类别')),
            ],
            options={
                'verbose_name': '资产',
                'verbose_name_plural': '资产',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateTimeField(verbose_name='转移日期')),
                ('reason', models.TextField(verbose_name='转移原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset', verbose_name='资产')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to=settings.AUTH_USER_MODEL, verbose_name='转出人')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
            ],
            options={
                'verbose_name': '资产转移',
                'verbose_name_plural': '资产转移',
                'ordering': ['-transfer_date'],
            },
        ),
    ]
